version: "3.4"
services:
  
  storage-service:
    build:
      context: ./storage-service
      dockerfile: ./docker/dev/Dockerfile
    container_name: storage-service
    working_dir: /usr/local/storage-service
    environment:
      - NODE_ENV=local-stage
    volumes:
      - ./storage-service:/usr/local/storage-service
      - /usr/local/storage-service/node_modules/
    entrypoint: ./docker/dev/entrypoint.sh
    ports:
      - "8005:8005"
      - "5855:5855"
    networks:
      - ts-micro-net
  
  postgres:
    container_name: storage-data
    image: postgres
    environment:
      - POSTGRES_USER=sample
      - POSTGRES_PASSWORD=sample-pwd
      - POSTGRES_DB=sample
      - PGDATA=/data/postgres
    volumes:
      - postgres-storage-data:/data/postgres
      - ./storage-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - ts-micro-net
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin-storage-data:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - ts-micro-net
    restart: unless-stopped

volumes:
  postgres-storage-data:
  pgadmin-storage-data:

networks:
  ts-micro-net: